modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="mcw"
version="1.9.0"
displayName="mcw"
credits="Mod repris de Call of Duty Modern Warfare 3, est a été dirigée par Adrien Vischer avec l'aide d'une superbe amis"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Adrien Vischer"

[[dependencies.mcw]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




